### PR TITLE
refactor: use a regex to parse custom tags

### PR DESCRIPTION
**Pull request by florianvazelle**
Hi, I submit a PR that refactor the `_parse_custom_tags` method :wave: 

I use a regex to find custom tags. So in `next_message`, we can remove one call to `parse_bbcode`, because otherwise the other/default text effects didn't work for me.

I run the example scene and this seems to work.

I'm open to feedback :slightly_smiling_face:

### CODE REVIEW

**Comment by night-glider** [comment]
Hi there. Thanks! I really appreciate your help, but I'm unsure about regex performance in godot. I'll try to test performance and post my thoughts later :)

**Comment by florianvazelle** [comment]
You're right, I test to benchmark the `_parse_custom_tags` on my side with [godotengine/godot-benchmarks](https://github.com/godotengine/godot-benchmarks).

I made a script [benchmark_regex.gd](https://gist.github.com/florianvazelle/bcc129883d46098a6ad09779c325326f), which can be included in the benchmark suite, and the regex seems faster than the previous solution :slightly_smiling_face:

The result:
```json
{
	"benchmarks": [
		{
			"category": "Gdscript > Iteration",
			"name": "Original Parse Custom Tags Solution",
			"results": {
				"idle": 0,
				"physics": 0,
				"render_cpu": 0,
				"render_gpu": 0,
				"time": 24290		# <- Initial solution with 1000 iterations
			}
		},
		{
			"category": "Gdscript > Iteration",
			"name": "Regex Parse Custom Tags Solution",
			"results": {
				"idle": 0,
				"physics": 0,
				"render_cpu": 0,
				"render_gpu": 0,
				"time": 2157		# <- regex solution with 1000 iterations
			}
		}
	],
	"engine": {
		"binary_size": 103904256,
		"build_type": "editor",
		"version": "v4.2.1.stable.arch_linux",
		"version_hash": "unknown"
	},
	"system": {
		"cpu_architecture": "x86_64",
		"cpu_count": 8,
		"cpu_name": "Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz",
		"gpu_name": "Intel(R) HD Graphics 530 (SKL GT2)",
		"gpu_vendor": "Intel",
		"os": "Linux"
	}
}
```

**Comment by night-glider** [comment]
Wow, didn't know that regex is this fast in godot! Thanks a lot!

**Comment by night-glider** [comment]
And one more thing. I saw you reformatted my code as well (thanks btw). Did you do it manually?

**Comment by florianvazelle** [comment]
No, I use the `gdformat` command, provided by [godot-gdscript-toolkit](https://github.com/Scony/godot-gdscript-toolkit).

It's a great tool that can be used with pre-commit or in CI, to ensure that the code is formatted 🙂

**Pull request merged**
